name: scanner
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  google_ml_kit: ^0.6.0  
  path_provider: ^2.1.2
  tflite: ^1.1.2
  cupertino_icons: ^1.0.6
  camera: ^0.9.4+5
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:


 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  assets:
    - lib\assets\overlay.jpeg
    - lib\assets\try.tflite

